# Build stage
FROM node:18 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci 
COPY . ./
RUN npm run build

FROM nginx:1.23
COPY --from=build /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

# Copy Nginx config
# Copy SSL certificates
COPY origin.pem /etc/nginx/certs/origin.pem
COPY private.pem /etc/nginx/certs/private.pem

# Expose port
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
